services:
  - type: web
    name: tubipure-app
    runtime: docker
    plan: free
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: APP_NAME
        value: TubiPure
      - key: APP_ENV
        value: production
      - key: APP_TIMEZONE
        value: Asia/Manila
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: tubipure-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: tubipure-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: tubipure-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: tubipure-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tubipure-db
          property: password
      - key: TUBIPURE_ADMIN_EMAIL
        sync: false
      - key: TUBIPURE_ADMIN_PASSWORD
        sync: false

databases:
  - name: tubipure-db
    plan: free
    databaseName: tubipure
    user: tubipure
